## UserResourceType (object)
+ type: `users`

## UserResourceIdentifier (ResourceIdentifier)
+ Include UserResourceType

## UserResourceAttributes (object)
+ attributes (object)
    + username: `the-username` (string)
    + dateRegistered: `2019-12-11` (string)
    + createdBy: `1253` (string) - id of user that created the user

## UserResource (ResourceObject)
+ Include UserResourceIdentifier
+ Include UserResourceAttributes
