## {RESOURCE_NAME}ResourceType (object)
+ type: `{RESOURCE_TYPE_NAME}`

## {RESOURCE_NAME}ResourceIdentifier (ResourceIdentifier)
+ Include {RESOURCE_NAME}ResourceType

## {RESOURCE_NAME}ResourceAttributes (object)
+ attributes (object)

## {RESOURCE_NAME}Resource (ResourceObject)
+ Include {RESOURCE_NAME}ResourceIdentifier
+ Include {RESOURCE_NAME}ResourceAttributes
