# Group Users

## User [/users/{id}]

+ Parameters
    + id (string)
        The id of desired resource.

### Retrieve User [GET]
Endpoint allows consumer to retrieve a resource.

+ Response 200 (application/json)
    + Attributes (UserResponse)
+ Response 404 (application/json)
    + Attributes (ResourceNotFoundResponse)
+ Response 422 (application/json)
    + Attributes (UnprocessableEntityResponse)
    
### Update User [PATCH]
Endpoint allows consumer to update an existing resource.

+ Request (application/json)
    + Attributes (UpdateUserRequest)
+ Response 200 (application/json)
    + Attributes (UserResponse)
+ Response 404 (application/json)
    + Attributes (ResourceNotFoundResponse)
+ Response 422 (application/json)
    + Attributes (UnprocessableEntityResponse)

### Remove User [DELETE]
Endpoint allows consumer to remove existing resource.

+ Response 204 (application/json)
+ Response 404 (application/json)
    + Attributes (ResourceNotFoundResponse)

## Users [/users]

### Retrieve Users [GET]
Endpoint allows consumer to retrieve collection of resources.

+ Response 200 (application/json)
    + Attributes (UsersResponse)

### Create User [POST]
Endpoint allows consumer to create new resource.

+ Request (application/json)
    + Attributes (CreateUserRequest)
+ Response 201 (application/json)
    + Headers

            Location: /users/{id}

    + Attributes (UserResponse)
+ Response 422 (application/json)
    + Attributes (UnprocessableEntityResponse)

## Data Structures

## UserResponse (ResourceResponse)
+ data (UserResource)

## UsersResponse (CollectionResponse)
+ data (array[UserResource])

## UpdateUserRequest (ResourceRequest)
+ data (UserResource)

## CreateUserRequest (ResourceRequest)
+ data (object)
    + Include UserResourceType
    + Include UserResourceAttributes
