<!-- include(../src/api-description.apib) -->

<!-- include(../build/groups.apib) -->

# Data Structures
<!-- include(jsonapi/index.apib) -->
<!-- include(../src/requests.apib) -->
<!-- include(../src/responses.apib) -->
<!-- include(../build/resources.apib) -->
