## ResourceResponse (ResourceJsonApiResponse)

## CollectionResponse (CollectionJsonApiResponse)

## ErrorsResponse (ErrorsJsonApiResponse)

## ResourceNotFoundResponse (ErrorsResponse)
+ errors (array[ResourceNotFoundErrorObject])

## UnprocessableEntityResponse (ErrorsResponse)
+ errors (array[InvalidAttributeErrorObject])
